spring:
  profiles.include: common
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: ${axon.command-bus.executor.pool-size}
  jpa:
    database-platform: me.mdjnewman.vetted.importer.PostgreSQLDialectCustom
    hibernate.ddl-auto: update
