package me.mdjnewman.vetted.coreinfrastructure

import org.springframework.context.annotation.ComponentScan
import org.springframework.context.annotation.Configuration

@Configuration
@ComponentScan
interface VettedCoreInfrastructureConfig