version: '3'
services:
  es:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2"
    ports:
      - "9200:9200"
      - "9300:930"
    environment:
      - "discovery.type=single-node"
  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:6.2.2"
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://192.168.0.20:9200" # TODO
    depends_on:
      - es
  postgres:
    image: "postgres:10"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=vetted-superuser"
